version: '3'

services:

  # Container
  applicants.api:
    # Image name to start the container from
    image: applicants.api       

    # Contains the path to the dockerfile to use and the context
    build:
      context: ./services/applicants.api
      dockerfile: Dockerfile.debug

    # Exposes ports to the host machine
    ports: 
    - "8081:80"

    # Allows mount pahts on host inside the container. Useful to debuggigng
    volumes: 
      - ./services/applicants.api/bin/pub/:/app

    # Custom name for container
    container_name: applicants.api

  identity.api:
    image: identity.api
    build:
      context: ./services/identity.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8084:80"
    volumes: 
      - ./services/identity.api/bin/pub/:/app
    container_name: identity.api     

  jobs.api:
    image: jobs.api
    build:
      context: ./services/jobs.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8083:80"
    volumes: 
      - ./services/jobs.api/bin/pub/:/app
    container_name: jobs.api

  # Don't containerize database in production
  sql.data:
    image: mssql-linux
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "5433:1433"
    container_name: mssql-linux